# Generated by Django 2.2.1 on 2020-03-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duapola_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='color',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='duapola_backend.Color'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='size',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='duapola_backend.Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
