# Generated by Django 2.2.1 on 2020-03-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duapola_backend', '0004_cart_cartitem_historicalcart_historicalcartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcart',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
