# Generated by Django 2.2.13 on 2020-06-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragnarok', '0003_auto_20200624_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guildwarteam',
            name='guild_war',
        ),
        migrations.RemoveField(
            model_name='guildwarteam',
            name='team',
        ),
        migrations.RemoveField(
            model_name='historicalguildwar',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalguildwarteam',
            name='guild_war',
        ),
        migrations.RemoveField(
            model_name='historicalguildwarteam',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalguildwarteam',
            name='team',
        ),
        migrations.DeleteModel(
            name='GuildWar',
        ),
        migrations.DeleteModel(
            name='GuildWarTeam',
        ),
        migrations.DeleteModel(
            name='HistoricalGuildWar',
        ),
        migrations.DeleteModel(
            name='HistoricalGuildWarTeam',
        ),
    ]
