# Generated by Django 2.2.13 on 2020-06-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ragnarok', '0009_historicalsimulator_historicalsimulatorattribute_simulator_simulatorattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essenceelement',
            name='essence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='ragnarok.Essence'),
        ),
        migrations.AlterField(
            model_name='monsterelement',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='ragnarok.Monster'),
        ),
    ]
