# Generated by Django 2.2.13 on 2020-06-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragnarok', '0010_auto_20200626_0048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalResonaceRecipe',
            new_name='HistoricalResonanceRecipe',
        ),
        migrations.RenameModel(
            old_name='ResonaceRecipe',
            new_name='ResonanceRecipe',
        ),
        migrations.AlterModelOptions(
            name='historicalresonancerecipe',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical resonance recipe'},
        ),
    ]
